<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220314184150 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_CART_REFERENCE_USERS');
        $this->addSql('ALTER TABLE cart CHANGE ID_cart ID_cart INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7F8371B55 FOREIGN KEY (ID_USER) REFERENCES users (ID_USER)');
        $this->addSql('ALTER TABLE category CHANGE ID_CATEGORY ID_CATEGORY INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_COMMENTS_REFERENCE_NEWS');
        $this->addSql('ALTER TABLE comments CHANGE ID_COMMENT ID_COMMENT INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A6877544C FOREIGN KEY (ID_NEWS) REFERENCES news (ID_NEWS)');
        $this->addSql('ALTER TABLE competitions DROP FOREIGN KEY FK_COMPETIT_REFERENCE_GAMES');
        $this->addSql('ALTER TABLE competitions CHANGE ID_COMPETION ID_COMPETION INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE competitions ADD CONSTRAINT FK_A7DD463D568FFC90 FOREIGN KEY (ID_GAME) REFERENCES games (ID_GAME)');
        $this->addSql('ALTER TABLE games DROP FOREIGN KEY FK_GAMES_REFERENCE_CATEGORY');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT FK_FF232B315965E51F FOREIGN KEY (ID_CATEGORY) REFERENCES category (ID_CATEGORY)');
        $this->addSql('ALTER TABLE groups CHANGE ID_GROUP ID_GROUP INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE news CHANGE ID_NEWS ID_NEWS INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_PRODUCT_REFERENCE_CATEGORY');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_PRODUCT_REFERENCE_CART');
        $this->addSql('ALTER TABLE product CHANGE ID_PRODUCT ID_PRODUCT INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD5965E51F FOREIGN KEY (ID_CATEGORY) REFERENCES category (ID_CATEGORY)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD4892A81F FOREIGN KEY (ID_cart) REFERENCES cart (ID_cart)');
        $this->addSql('ALTER TABLE teams DROP FOREIGN KEY FK_TEAMS_REFERENCE_COMPETIT');
        $this->addSql('ALTER TABLE teams CHANGE ID_TEAM ID_TEAM INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE teams ADD CONSTRAINT FK_96C222588BD3C9B5 FOREIGN KEY (ID_COMPETION) REFERENCES competitions (ID_COMPETION)');
        $this->addSql('ALTER TABLE trophies DROP FOREIGN KEY FK_TROPHIES_REFERENCE_GAMES');
        $this->addSql('ALTER TABLE trophies ADD CONSTRAINT FK_5EAD4C66568FFC90 FOREIGN KEY (ID_GAME) REFERENCES games (ID_GAME)');
        $this->addSql('ALTER TABLE tutorials DROP FOREIGN KEY FK_TUTORIAL_REFERENCE_USERS');
        $this->addSql('ALTER TABLE tutorials DROP FOREIGN KEY FK_TUTORIAL_REFERENCE_TROPHIES');
        $this->addSql('ALTER TABLE tutorials ADD CONSTRAINT FK_C21EFE28F8371B55 FOREIGN KEY (ID_USER) REFERENCES users (ID_USER)');
        $this->addSql('ALTER TABLE tutorials ADD CONSTRAINT FK_C21EFE28BC626877 FOREIGN KEY (ID_TROPHY) REFERENCES trophies (ID_TROPHY)');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_USERS_REFERENCE_GROUPS');
        $this->addSql('ALTER TABLE users CHANGE ID_USER ID_USER INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E942DA9C8F FOREIGN KEY (ID_GROUP) REFERENCES groups (ID_GROUP)');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_MEMBERS_REFERENCE_USERS');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_MEMBERS_REFERENCE_TEAMS');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_MEMBERS_REFERENCE_TEAMS');
        $this->addSql('ALTER TABLE members ADD CONSTRAINT FK_45A0D2FFF8371B55 FOREIGN KEY (ID_USER) REFERENCES users (ID_USER)');
        $this->addSql('ALTER TABLE members ADD CONSTRAINT FK_45A0D2FFB1446B03 FOREIGN KEY (ID_TEAM) REFERENCES teams (ID_TEAM)');
        $this->addSql('DROP INDEX fk_members_reference_teams ON members');
        $this->addSql('CREATE INDEX IDX_45A0D2FFB1446B03 ON members (ID_TEAM)');
        $this->addSql('ALTER TABLE members ADD CONSTRAINT FK_MEMBERS_REFERENCE_TEAMS FOREIGN KEY (ID_TEAM) REFERENCES teams (ID_TEAM) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_USERTEAM_REFERENCE_TEAMS');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_USERTEAM_REFERENCE_GAMES');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_USERTEAM_REFERENCE_USERS');
        $this->addSql('ALTER TABLE userteams DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE userteams ADD CONSTRAINT FK_B1661E8AB1446B03 FOREIGN KEY (ID_TEAM) REFERENCES teams (ID_TEAM)');
        $this->addSql('ALTER TABLE userteams ADD CONSTRAINT FK_B1661E8A568FFC90 FOREIGN KEY (ID_GAME) REFERENCES games (ID_GAME)');
        $this->addSql('ALTER TABLE userteams ADD CONSTRAINT FK_B1661E8AF8371B55 FOREIGN KEY (ID_USER) REFERENCES users (ID_USER)');
        $this->addSql('ALTER TABLE userteams ADD PRIMARY KEY (ID_TEAM, ID_GAME, ID_USER)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7F8371B55');
        $this->addSql('ALTER TABLE cart CHANGE ID_cart ID_cart INT NOT NULL');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_CART_REFERENCE_USERS FOREIGN KEY (ID_USER) REFERENCES users (ID_USER) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category CHANGE ID_CATEGORY ID_CATEGORY INT NOT NULL, CHANGE CATEGORY CATEGORY VARCHAR(30) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A6877544C');
        $this->addSql('ALTER TABLE comments CHANGE ID_COMMENT ID_COMMENT INT NOT NULL, CHANGE COMMENT COMMENT VARCHAR(512) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_COMMENTS_REFERENCE_NEWS FOREIGN KEY (ID_NEWS) REFERENCES news (ID_NEWS) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE competitions DROP FOREIGN KEY FK_A7DD463D568FFC90');
        $this->addSql('ALTER TABLE competitions CHANGE ID_COMPETION ID_COMPETION INT NOT NULL, CHANGE GAME_NAME GAME_NAME VARCHAR(30) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE competitions ADD CONSTRAINT FK_COMPETIT_REFERENCE_GAMES FOREIGN KEY (ID_GAME) REFERENCES games (ID_GAME) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE games DROP FOREIGN KEY FK_FF232B315965E51F');
        $this->addSql('ALTER TABLE games CHANGE NAME NAME VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE DESCRIPTION DESCRIPTION TEXT DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE img img VARCHAR(1000) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT FK_GAMES_REFERENCE_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES category (ID_CATEGORY) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groups CHANGE ID_GROUP ID_GROUP INT NOT NULL, CHANGE NAME NAME VARCHAR(50) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE IMG IMG VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_45A0D2FFF8371B55');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_45A0D2FFB1446B03');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_45A0D2FFB1446B03');
        $this->addSql('ALTER TABLE members ADD CONSTRAINT FK_MEMBERS_REFERENCE_USERS FOREIGN KEY (ID_USER) REFERENCES users (ID_USER) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE members ADD CONSTRAINT FK_MEMBERS_REFERENCE_TEAMS FOREIGN KEY (ID_TEAM) REFERENCES teams (ID_TEAM) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_45a0d2ffb1446b03 ON members');
        $this->addSql('CREATE INDEX FK_MEMBERS_REFERENCE_TEAMS ON members (ID_TEAM)');
        $this->addSql('ALTER TABLE members ADD CONSTRAINT FK_45A0D2FFB1446B03 FOREIGN KEY (ID_TEAM) REFERENCES teams (ID_TEAM)');
        $this->addSql('ALTER TABLE news CHANGE ID_NEWS ID_NEWS INT NOT NULL, CHANGE HEADLINE HEADLINE VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE CONTENT CONTENT TEXT DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE IMG IMG VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD5965E51F');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD4892A81F');
        $this->addSql('ALTER TABLE product CHANGE ID_PRODUCT ID_PRODUCT INT NOT NULL, CHANGE PROD_NAME PROD_NAME VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_PRODUCT_REFERENCE_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES category (ID_CATEGORY) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_PRODUCT_REFERENCE_CART FOREIGN KEY (ID_cart) REFERENCES cart (ID_cart) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teams DROP FOREIGN KEY FK_96C222588BD3C9B5');
        $this->addSql('ALTER TABLE teams CHANGE ID_TEAM ID_TEAM INT NOT NULL, CHANGE TEAM_NAME TEAM_NAME VARCHAR(50) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE CREATOR CREATOR VARCHAR(50) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE teams ADD CONSTRAINT FK_TEAMS_REFERENCE_COMPETIT FOREIGN KEY (ID_COMPETION) REFERENCES competitions (ID_COMPETION) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trophies DROP FOREIGN KEY FK_5EAD4C66568FFC90');
        $this->addSql('ALTER TABLE trophies CHANGE TITLE TITLE VARCHAR(30) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE DESCRIPTION DESCRIPTION VARCHAR(1000) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE PLATFORM PLATFORM VARCHAR(20) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE DIFFICULITY DIFFICULITY VARCHAR(20) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE trophies ADD CONSTRAINT FK_TROPHIES_REFERENCE_GAMES FOREIGN KEY (ID_GAME) REFERENCES games (ID_GAME) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tutorials DROP FOREIGN KEY FK_C21EFE28F8371B55');
        $this->addSql('ALTER TABLE tutorials DROP FOREIGN KEY FK_C21EFE28BC626877');
        $this->addSql('ALTER TABLE tutorials CHANGE PATH PATH VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE CONTENT CONTENT TEXT DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE tutorials ADD CONSTRAINT FK_TUTORIAL_REFERENCE_USERS FOREIGN KEY (ID_USER) REFERENCES users (ID_USER) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tutorials ADD CONSTRAINT FK_TUTORIAL_REFERENCE_TROPHIES FOREIGN KEY (ID_TROPHY) REFERENCES trophies (ID_TROPHY) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E942DA9C8F');
        $this->addSql('ALTER TABLE users CHANGE ID_USER ID_USER INT NOT NULL, CHANGE FULL_NAME FULL_NAME VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE IMG IMG VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE EMAIL EMAIL VARCHAR(50) DEFAULT NULL COLLATE `utf8mb4_general_ci`, CHANGE PASSWORD PASSWORD VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_USERS_REFERENCE_GROUPS FOREIGN KEY (ID_GROUP) REFERENCES groups (ID_GROUP) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_B1661E8AB1446B03');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_B1661E8A568FFC90');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_B1661E8AF8371B55');
        $this->addSql('ALTER TABLE userteams DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE userteams ADD CONSTRAINT FK_USERTEAM_REFERENCE_TEAMS FOREIGN KEY (ID_TEAM) REFERENCES teams (ID_TEAM) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userteams ADD CONSTRAINT FK_USERTEAM_REFERENCE_GAMES FOREIGN KEY (ID_GAME) REFERENCES games (ID_GAME) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userteams ADD CONSTRAINT FK_USERTEAM_REFERENCE_USERS FOREIGN KEY (ID_USER) REFERENCES users (ID_USER) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE userteams ADD PRIMARY KEY (ID_TEAM, ID_USER, ID_GAME)');
    }
}
