<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220414141105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cart (ID_cart INT AUTO_INCREMENT NOT NULL, ID_USER INT DEFAULT NULL, SUM DOUBLE PRECISION DEFAULT NULL, DISCOUNT DOUBLE PRECISION DEFAULT NULL, INDEX FK_CART_REFERENCE_USERS (ID_USER), PRIMARY KEY(ID_cart)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (ID_CATEGORY INT AUTO_INCREMENT NOT NULL, CATEGORY VARCHAR(30) DEFAULT NULL, PRIMARY KEY(ID_CATEGORY)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comments (ID_COMMENT INT AUTO_INCREMENT NOT NULL, COMMENT VARCHAR(512) NOT NULL, LIKES INT DEFAULT NULL, DISLIKES INT DEFAULT NULL, ID_NEWS INT DEFAULT NULL, INDEX FK_COMMENTS_REFERENCE_NEWS (ID_NEWS), PRIMARY KEY(ID_COMMENT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competitions (ID_COMPETION INT AUTO_INCREMENT NOT NULL, GAME_NAME VARCHAR(30) DEFAULT NULL, DATEOFCOMP DATE DEFAULT NULL, PRIMARY KEY(ID_COMPETION)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE games (ID_GAME INT AUTO_INCREMENT NOT NULL, ID_CATEGORY INT DEFAULT NULL, NAME VARCHAR(100) DEFAULT NULL, DESCRIPTION TEXT DEFAULT NULL, RATE NUMERIC(8, 4) DEFAULT NULL, INDEX FK_GAMES_REFERENCE_CATEGORY (ID_CATEGORY), PRIMARY KEY(ID_GAME)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE members (ID_USER INT NOT NULL, ID_TEAM INT NOT NULL, INDEX FK_MEMBERS_REFERENCE_TEAMS (ID_TEAM), PRIMARY KEY(ID_USER, ID_TEAM)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE news (ID_NEWS INT AUTO_INCREMENT NOT NULL, HEADLINE VARCHAR(100) DEFAULT NULL, CONTENT TEXT DEFAULT NULL, IMG VARCHAR(200) DEFAULT NULL, PRIMARY KEY(ID_NEWS)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `order` (OrderID INT AUTO_INCREMENT NOT NULL, CardNumber VARCHAR(220) NOT NULL, CardPassword VARCHAR(140) NOT NULL, Name VARCHAR(100) NOT NULL, Month INT NOT NULL, Year INT NOT NULL, PRIMARY KEY(OrderID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (ID_PRODUCT INT AUTO_INCREMENT NOT NULL, PROD_NAME VARCHAR(100) DEFAULT NULL, PRICE DOUBLE PRECISION DEFAULT NULL, Category VARCHAR(200) NOT NULL, DISCOUNT DOUBLE PRECISION DEFAULT NULL, Quantity INT NOT NULL, PRIMARY KEY(ID_PRODUCT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teams (ID_TEAM INT AUTO_INCREMENT NOT NULL, ID_COMPETION INT DEFAULT NULL, TEAM_NAME VARCHAR(50) DEFAULT NULL, INDEX FK_TEAMS_REFERENCE_COMPETIT (ID_COMPETION), PRIMARY KEY(ID_TEAM)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trophies (ID_TROPHY INT AUTO_INCREMENT NOT NULL, ID_GAME INT DEFAULT NULL, TITLE VARCHAR(30) DEFAULT NULL, DESCRIPTION VARCHAR(1000) DEFAULT NULL, PLATFORM VARCHAR(20) DEFAULT NULL, DIFFICULITY VARCHAR(20) DEFAULT NULL, INDEX FK_TROPHIES_REFERENCE_GAMES (ID_GAME), PRIMARY KEY(ID_TROPHY)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tutorials (ID_TUTORIAL INT AUTO_INCREMENT NOT NULL, ID_USER INT DEFAULT NULL, ID_TROPHY INT DEFAULT NULL, PATH VARCHAR(200) DEFAULT NULL, CONTENT TEXT DEFAULT NULL, INDEX FK_TUTORIAL_REFERENCE_TROPHIES (ID_TROPHY), INDEX FK_TUTORIAL_REFERENCE_USERS (ID_USER), PRIMARY KEY(ID_TUTORIAL)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_groups (ID_USERS_GPS INT AUTO_INCREMENT NOT NULL, status VARCHAR(20) NOT NULL, ID_GROUP INT DEFAULT NULL, ID_USER INT DEFAULT NULL, INDEX fk_ID_GROUP (ID_GROUP), INDEX fk_ID_USER (ID_USER), PRIMARY KEY(ID_USERS_GPS)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (ID_USER INT AUTO_INCREMENT NOT NULL, FULL_NAME VARCHAR(100) DEFAULT NULL, EMAIL VARCHAR(50) DEFAULT NULL, PASSWORD VARCHAR(200) DEFAULT NULL, ISACTIVE TINYINT(1) DEFAULT NULL, PRIVILEGE_ TINYINT(1) DEFAULT NULL, PRIMARY KEY(ID_USER)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE userteams (ID_TEAM INT NOT NULL, ID_USER INT NOT NULL, ID_GAME INT NOT NULL, INDEX FK_USERTEAM_REFERENCE_GAMES (ID_GAME), INDEX FK_USERTEAM_REFERENCE_USERS (ID_USER), PRIMARY KEY(ID_TEAM, ID_USER, ID_GAME)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A6877544C FOREIGN KEY (ID_NEWS) REFERENCES news (ID_NEWS)');
        
        
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A6877544C');
       
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE comments');
        $this->addSql('DROP TABLE competitions');
        $this->addSql('DROP TABLE games');
        $this->addSql('DROP TABLE groups');
        $this->addSql('DROP TABLE members');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE `order`');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE teams');
        $this->addSql('DROP TABLE trophies');
        $this->addSql('DROP TABLE tutorials');
        $this->addSql('DROP TABLE user_groups');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE userteams');
    }

    public function isTransactional(): bool
    {
        return false;
    }

}
