<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220402212737 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE `groups` (ID_GROUP INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) DEFAULT NULL, IMG VARCHAR(200) DEFAULT NULL, PRIMARY KEY(ID_GROUP)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE groupss');
        $this->addSql('DROP TABLE product');
        $this->addSql('ALTER TABLE cart CHANGE ID_cart ID_cart INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE category ADD type VARCHAR(255) NOT NULL, DROP CATEGORY, CHANGE ID_CATEGORY ID_CATEGORY INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE comments CHANGE ID_COMMENT ID_COMMENT INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE competitions CHANGE ID_COMPETION ID_COMPETION INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE games ADD img VARCHAR(1000) DEFAULT NULL, CHANGE DESCRIPTION DESCRIPTION TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE news CHANGE ID_NEWS ID_NEWS INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE teams CHANGE ID_TEAM ID_TEAM INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE trophies DROP GAM_ID_GAME');
        $this->addSql('ALTER TABLE users CHANGE ID_USER ID_USER INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE users RENAME INDEX fk_users_reference_groupss TO FK_USERS_REFERENCE_GROUPS');
        $this->addSql('CREATE INDEX IDX_45A0D2FFF8371B55 ON members (ID_USER)');
        $this->addSql('ALTER TABLE members RENAME INDEX fk_members_reference_teams TO IDX_45A0D2FFB1446B03');
        $this->addSql('ALTER TABLE userteams DROP PRIMARY KEY');
        $this->addSql('CREATE INDEX IDX_B1661E8AB1446B03 ON userteams (ID_TEAM)');
        $this->addSql('ALTER TABLE userteams ADD PRIMARY KEY (ID_TEAM, ID_GAME, ID_USER)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E942DA9C8F');
        $this->addSql('CREATE TABLE groupss (ID_GROUP INT NOT NULL, NAME_GROUP VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, IMG VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, PRIMARY KEY(ID_GROUP)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE product (ID_PRODUCT INT NOT NULL, ID_CATEGORY INT DEFAULT NULL, ID_cart INT DEFAULT NULL, PROD_NAME VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, PRICE DOUBLE PRECISION DEFAULT NULL, DISCOUNT TINYINT(1) DEFAULT NULL, INDEX FK_PRODUCT_REFERENCE_CART (ID_cart), INDEX FK_PRODUCT_REFERENCE_CATEGORY (ID_CATEGORY), PRIMARY KEY(ID_PRODUCT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('DROP TABLE `groups`');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7F8371B55');
        $this->addSql('ALTER TABLE cart CHANGE ID_cart ID_cart INT NOT NULL');
        $this->addSql('ALTER TABLE category ADD CATEGORY VARCHAR(30) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, DROP type, CHANGE ID_CATEGORY ID_CATEGORY INT NOT NULL');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A6877544C');
        $this->addSql('ALTER TABLE comments CHANGE ID_COMMENT ID_COMMENT INT NOT NULL, CHANGE COMMENT COMMENT VARCHAR(512) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE competitions DROP FOREIGN KEY FK_A7DD463D568FFC90');
        $this->addSql('ALTER TABLE competitions CHANGE ID_COMPETION ID_COMPETION INT NOT NULL, CHANGE GAME_NAME GAME_NAME VARCHAR(30) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE games DROP FOREIGN KEY FK_FF232B315965E51F');
        $this->addSql('ALTER TABLE games DROP img, CHANGE NAME NAME VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE DESCRIPTION DESCRIPTION VARCHAR(1000) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_45A0D2FFF8371B55');
        $this->addSql('ALTER TABLE members DROP FOREIGN KEY FK_45A0D2FFB1446B03');
        $this->addSql('DROP INDEX IDX_45A0D2FFF8371B55 ON members');
        $this->addSql('ALTER TABLE members RENAME INDEX idx_45a0d2ffb1446b03 TO FK_MEMBERS_REFERENCE_TEAMS');
        $this->addSql('ALTER TABLE news CHANGE ID_NEWS ID_NEWS INT NOT NULL, CHANGE HEADLINE HEADLINE VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE CONTENT CONTENT TEXT DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE IMG IMG VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE teams DROP FOREIGN KEY FK_96C222588BD3C9B5');
        $this->addSql('ALTER TABLE teams CHANGE ID_TEAM ID_TEAM INT NOT NULL, CHANGE TEAM_NAME TEAM_NAME VARCHAR(50) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE CREATOR CREATOR VARCHAR(50) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE trophies DROP FOREIGN KEY FK_5EAD4C66568FFC90');
        $this->addSql('ALTER TABLE trophies ADD GAM_ID_GAME INT DEFAULT NULL, CHANGE TITLE TITLE VARCHAR(30) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE DESCRIPTION DESCRIPTION VARCHAR(1000) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE PLATFORM PLATFORM VARCHAR(20) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE DIFFICULITY DIFFICULITY VARCHAR(20) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE tutorials DROP FOREIGN KEY FK_C21EFE28F8371B55');
        $this->addSql('ALTER TABLE tutorials DROP FOREIGN KEY FK_C21EFE28BC626877');
        $this->addSql('ALTER TABLE tutorials CHANGE PATH PATH VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE CONTENT CONTENT TEXT DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE users CHANGE ID_USER ID_USER INT NOT NULL, CHANGE FULL_NAME FULL_NAME VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE IMG IMG VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE EMAIL EMAIL VARCHAR(50) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, CHANGE PASSWORD PASSWORD VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`');
        $this->addSql('ALTER TABLE users RENAME INDEX fk_users_reference_groups TO FK_USERS_REFERENCE_GROUPSS');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_B1661E8AB1446B03');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_B1661E8A568FFC90');
        $this->addSql('ALTER TABLE userteams DROP FOREIGN KEY FK_B1661E8AF8371B55');
        $this->addSql('DROP INDEX IDX_B1661E8AB1446B03 ON userteams');
        $this->addSql('ALTER TABLE userteams DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE userteams ADD PRIMARY KEY (ID_TEAM, ID_USER, ID_GAME)');
    }
}
