#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login

# /app/config/routes.yaml
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"