#index:
#    path: /
#    controller: App\Controller\DefaultController::index
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor

api_login_check:
  path: /api/login

# /app/config/routes.yaml
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
